<a href="mailto:<? echo $admin_email;?>?subject=Werbung">
<img src="images/pb_button2.gif" border= "0" vspace="2" hspace="1" align="center"></a>
<a href="http://www.smartisoft.com">
<img src="images/pb_button3.gif" height="130" width="120" border= "0" vspace="6" hspace="1" align="center"></a>
<a href="mailto:<? echo $admin_email;?>?subject=Werbung">
<img src="images/pb_button2.gif" border= "0" vspace="2" hspace="1" align="center"></a>
