<script language="JavaScript">
<!-- Cloak Engaged
//MSIE 4.x Detection
  if ((navigator.appName == "Microsoft Internet Explorer") && (parseInt(navigator.appVersion) >= 4 ))
     {}
  else
     {alert("Le site est optimisé pour MS Internet Explorer 4.0. et versions plus récentes avec une résolution minimale de 800x600 ! Vous employez un autre navigateur, il est donc possible que les pages ne s'affichent pas correctement.");}
//-- Cloak Disengaged -->
</script>

