<div class="mainheader">Confirmation</div>
<div class="maintext">
<br>
Votre enregistrement est confirmé.<br>
Votre pseudo est <? echo $nick; ?>.<br>
<br>
Dès maintenant vous pouvez vous connecter avec votre pseudo et votre mot de passe.<br>
<br><center>
<input type=submit value="Connexion" onClick="window.location.href='main.php'">
<input type=submit value="Fermer" onClick="window.close()">
</center>
</div>