<br>
<table><tr><td colspan="2">
Contacter <em id="red">smartisoft.com</em> :<br>
<br>
</td></tr>
<tr><td>
Webmaster :
</td><td>
<a href="mailto:webmaster@smartisoft.com">webmaster@smartisoft.com</a><br>
</td></tr>
<tr><td>
Support   :
</td><td>
<a href="mailto:support@smartisoft.com">support@smartisoft.com</a><br>
</td></tr>
<tr><td>
Marketing :
</td><td>
<a href="mailto:marketing@smartisoft.com">marketing@smartisoft.com</a><br>
</td></tr>
<tr><td>
Bureau :
</td><td>
<a href="mailto:support@phplogix.com">support@phplogix.com</a><br>
</td></tr>
<tr><td><br>
Localisation  :
</td><td><br>
Le monde<br>
</td></tr>
<tr><td>
Software  :
</td><td>
Logix Classifieds <? echo $bazar_version?><br>
</td></tr>
<br>
</table>