<div class="mainheader">Non connecté</div>
<div class="maintext">
<br>
Désolé, vous n'êtes pas connecté ...<br>
<br>
Veuillez vous connecter dans la fenêtre de gauche. Si vous n'avez pas de pseudo et de mot de passe inscrivez-vous dès maintenant à <? echo $bazar_name;?> gratuitement !<br>
<br>
Il n'y a pas de coût caché ou autre, alors n'attendez pas pour vous enregistrer et obtenir le meilleur de l'annonce répertoriée du NET.<br>
</div>
