<div class="mainheader">Merci<p><div>
<div class="maintext">
<br>
Vous êtes enregistré (en attente de validation).<br>
Un E-Mail a été envoyé à <b><? echo "$email";?></b><br>
<br>
Pour compléter votre inscription, vous devez consulter vos E-Mails et cliquer sur le lien pour confirmer la création de votre compte. Vous pourrez ensuite accéder aux services avec votre pseudo et votre mot de passe.<BR><BR> Si vous ne confirmez pas votre inscription sous 48 heures elle sera annulée.<br><br><center><form action=javascript:window.close() METHOD=POST><input type=submit value=Fermer></form></center></div>