<br>
<DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
 <head>
   <title>Conditions d'utilisation</title>
     <link rel="stylesheet" type="text/css" href="<? echo $STYLE; ?>">
      <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
 </head>

<?echo"<body bgcolor=\"$bgcolor\">\n";?>

<div class="maintext">
Conditions d'utilisation<br><br>
Ici vous pouvez spécifier vos conditions d'utilisation<br><br>
</div>
</body>
</html>

