<div class="mainheader">Bienvenue</div>
<div class="maintext">
<br>
Bienvenue sur Logix Classifieds!<br>
<br>
C'est la page d'accueil de votre site !<br><br>
Si vous avez du contenu 'adulte' sur votre site, vous devez placer ici un avertissement.<br><br>
Ce site propose du contenu pour adulte ! Vous devez avoir 18 ans ou plus pour entrer. Si ce n'est pas la cas veuillez sortir.<br>
<br>
Merci.<br>
<br>
<center>
<a href="http://www.disney.com">Non, je n'ai pas encore 18 ans</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="main.php">Oui, j'ai 18 ans ou plus</a>
</center>
</div>
